# Integrated plugins list
# These plugins have been integrated into redmine_studio_plugin.
# If any of these plugins exist in the plugins folder, a conflict warning will be displayed.
#
# When adding a new integrated plugin:
# 1. Add the plugin name to this list
# 2. The conflict detection (init.rb) and install task (install.rake) will automatically use this list
# 3. Update TEST_SPEC.md files to reference this configuration

integrated_plugins:
  - redmine_reply_button
  - redmine_teams_button
  - redmine_auto_close
  - redmine_date_independent
